# Generated by Django 5.2.4 on 2025-07-24 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_asteroid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asteroid',
            name='date',
        ),
        migrations.AddField(
            model_name='asteroid',
            name='imported_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
