# Generated by Django 5.2.4 on 2025-07-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_asteroid_date_asteroid_imported_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
